version: '3'
services:
  web:
    container_name: bootcamp-eduzz
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - .:/src